// Code generated by ent, DO NOT EDIT.

package lock

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the lock type in the database.
	Label = "lock"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldVersionID holds the string denoting the versionid field in the database.
	FieldVersionID = "version_id"
	// FieldOwner holds the string denoting the owner field in the database.
	FieldOwner = "owner"
	// Table holds the table name of the lock in the database.
	Table = "dblock"
)

// Columns holds all SQL columns for lock fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldVersionID,
	FieldOwner,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultVersionID holds the default value on creation for the "versionID" field.
	DefaultVersionID func() uuid.UUID
)

// OrderOption defines the ordering options for the Lock queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByVersionID orders the results by the versionID field.
func ByVersionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersionID, opts...).ToFunc()
}

// ByOwner orders the results by the owner field.
func ByOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwner, opts...).ToFunc()
}
