// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DblockColumns holds the columns for the "dblock" table.
	DblockColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "version", Type: field.TypeUUID, Unique: true, Nullable: true},
		{Name: "owner", Type: field.TypeString},
	}
	// DblockTable holds the schema information for the "dblock" table.
	DblockTable = &schema.Table{
		Name:       "dblock",
		Columns:    DblockColumns,
		PrimaryKey: []*schema.Column{DblockColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DblockTable,
	}
)

func init() {
	DblockTable.Annotation = &entsql.Annotation{
		Table: "dblock",
	}
}
