// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shivanshvij/dblock/ent/lock"
	"github.com/shivanshvij/dblock/ent/predicate"
)

// LockUpdate is the builder for updating Lock entities.
type LockUpdate struct {
	config
	hooks     []Hook
	mutation  *LockMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the LockUpdate builder.
func (lu *LockUpdate) Where(ps ...predicate.Lock) *LockUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetVersion sets the "version" field.
func (lu *LockUpdate) SetVersion(u uuid.UUID) *LockUpdate {
	lu.mutation.SetVersion(u)
	return lu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (lu *LockUpdate) SetNillableVersion(u *uuid.UUID) *LockUpdate {
	if u != nil {
		lu.SetVersion(*u)
	}
	return lu
}

// ClearVersion clears the value of the "version" field.
func (lu *LockUpdate) ClearVersion() *LockUpdate {
	lu.mutation.ClearVersion()
	return lu
}

// SetOwner sets the "owner" field.
func (lu *LockUpdate) SetOwner(s string) *LockUpdate {
	lu.mutation.SetOwner(s)
	return lu
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (lu *LockUpdate) SetNillableOwner(s *string) *LockUpdate {
	if s != nil {
		lu.SetOwner(*s)
	}
	return lu
}

// Mutation returns the LockMutation object of the builder.
func (lu *LockUpdate) Mutation() *LockMutation {
	return lu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LockUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, lu.sqlSave, lu.mutation, lu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LockUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LockUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LockUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (lu *LockUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LockUpdate {
	lu.modifiers = append(lu.modifiers, modifiers...)
	return lu
}

func (lu *LockUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(lock.Table, lock.Columns, sqlgraph.NewFieldSpec(lock.FieldID, field.TypeString))
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.Version(); ok {
		_spec.SetField(lock.FieldVersion, field.TypeUUID, value)
	}
	if lu.mutation.VersionCleared() {
		_spec.ClearField(lock.FieldVersion, field.TypeUUID)
	}
	if value, ok := lu.mutation.Owner(); ok {
		_spec.SetField(lock.FieldOwner, field.TypeString, value)
	}
	_spec.AddModifiers(lu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lu.mutation.done = true
	return n, nil
}

// LockUpdateOne is the builder for updating a single Lock entity.
type LockUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *LockMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetVersion sets the "version" field.
func (luo *LockUpdateOne) SetVersion(u uuid.UUID) *LockUpdateOne {
	luo.mutation.SetVersion(u)
	return luo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (luo *LockUpdateOne) SetNillableVersion(u *uuid.UUID) *LockUpdateOne {
	if u != nil {
		luo.SetVersion(*u)
	}
	return luo
}

// ClearVersion clears the value of the "version" field.
func (luo *LockUpdateOne) ClearVersion() *LockUpdateOne {
	luo.mutation.ClearVersion()
	return luo
}

// SetOwner sets the "owner" field.
func (luo *LockUpdateOne) SetOwner(s string) *LockUpdateOne {
	luo.mutation.SetOwner(s)
	return luo
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (luo *LockUpdateOne) SetNillableOwner(s *string) *LockUpdateOne {
	if s != nil {
		luo.SetOwner(*s)
	}
	return luo
}

// Mutation returns the LockMutation object of the builder.
func (luo *LockUpdateOne) Mutation() *LockMutation {
	return luo.mutation
}

// Where appends a list predicates to the LockUpdate builder.
func (luo *LockUpdateOne) Where(ps ...predicate.Lock) *LockUpdateOne {
	luo.mutation.Where(ps...)
	return luo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LockUpdateOne) Select(field string, fields ...string) *LockUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Lock entity.
func (luo *LockUpdateOne) Save(ctx context.Context) (*Lock, error) {
	return withHooks(ctx, luo.sqlSave, luo.mutation, luo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LockUpdateOne) SaveX(ctx context.Context) *Lock {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LockUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LockUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (luo *LockUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LockUpdateOne {
	luo.modifiers = append(luo.modifiers, modifiers...)
	return luo
}

func (luo *LockUpdateOne) sqlSave(ctx context.Context) (_node *Lock, err error) {
	_spec := sqlgraph.NewUpdateSpec(lock.Table, lock.Columns, sqlgraph.NewFieldSpec(lock.FieldID, field.TypeString))
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Lock.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lock.FieldID)
		for _, f := range fields {
			if !lock.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.Version(); ok {
		_spec.SetField(lock.FieldVersion, field.TypeUUID, value)
	}
	if luo.mutation.VersionCleared() {
		_spec.ClearField(lock.FieldVersion, field.TypeUUID)
	}
	if value, ok := luo.mutation.Owner(); ok {
		_spec.SetField(lock.FieldOwner, field.TypeString, value)
	}
	_spec.AddModifiers(luo.modifiers...)
	_node = &Lock{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	luo.mutation.done = true
	return _node, nil
}
