// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/shivanshvij/dblock/ent/lock"
	"github.com/shivanshvij/dblock/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	lockMixin := schema.Lock{}.Mixin()
	lockMixinFields0 := lockMixin[0].Fields()
	_ = lockMixinFields0
	lockFields := schema.Lock{}.Fields()
	_ = lockFields
	// lockDescVersion is the schema descriptor for version field.
	lockDescVersion := lockMixinFields0[1].Descriptor()
	// lock.DefaultVersion holds the default value on creation for the version field.
	lock.DefaultVersion = lockDescVersion.Default.(func() uuid.UUID)
}
