name: Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

      - name: Test
        run: go test -v ./...

      - name: Test with Race Conditions
        run: go test -race -v ./...